### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method install on channel flutter_update))

### ISSUE THREAD

**Issue by 841660202** [YunlongYang/flutter_update#2]
![image](https://user-images.githubusercontent.com/18305361/54987513-b3925300-4fef-11e9-9d25-4765dcf2b3d8.png)

**Comment by YunlongYang** [comment]
第一个参数是应用主页，是给ios设备用的；
第二个参数是apk的本地路径, apk需要开发者自己实现下载到本地，是不是本地的apk文件不存在导致的呢？ @841660202

**Comment by YunlongYang** [comment]
@841660202 开发者最近没回应此问题，先关闭
